const path = '/assets/images/photos/';

export const photos = [
	{ alt: 'Steampunk heels', image: `${path}photo-001.jpg` },
	{ alt: 'Steampunk heels', image: `${path}photo-002.jpg` },
	{ alt: 'Steampunk heels', image: `${path}photo-003.jpg` },
	{ alt: 'Steampunk heels', image: `${path}photo-004.jpg` },
	{ alt: 'Steampunk heels', image: `${path}photo-005.jpg` },
	{ alt: 'Wedding dress', image: `${path}photo-006.jpg` },
	{ alt: 'Wedding dress', image: `${path}photo-007.jpg` },
	{ alt: 'Wedding dress', image: `${path}photo-008.jpg` },
	{ alt: 'Wedding dress', image: `${path}photo-009.jpg` },
	{ alt: 'Steampunk heels', image: `${path}photo-010.jpg` },
	{ alt: 'Antler decoration', image: `${path}photo-011.jpg` },
	{ alt: 'Elk at the Lodge at Elk Valley', image: `${path}photo-012.jpg` },
	{ alt: 'Elk at the Lodge at Elk Valley', image: `${path}photo-013.jpg` },
	{ alt: 'Makeup', image: `${path}photo-020.jpg` },
	{ alt: 'Matt getting ready', image: `${path}photo-025.jpg` },
	{ alt: 'Matt getting ready', image: `${path}photo-026.jpg` },
	{ alt: 'Matt getting ready', image: `${path}photo-029.jpg` },
	{ alt: 'Matt getting ready', image: `${path}photo-030.jpg` },
	{ alt: 'Matt getting ready', image: `${path}photo-031.jpg` },
	{ alt: 'Matt getting ready', image: `${path}photo-032.jpg` },
	{ alt: 'Matt posing', image: `${path}photo-037.jpg` },
	{ alt: 'Matt posing', image: `${path}photo-038.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-041.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-042.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-043.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-044.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-045.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-046.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-047.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-048.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-049.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-050.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-051.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-052.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-053.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-054.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-055.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-056.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-057.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-058.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-059.jpg` },
	{ alt: 'Adria in the woods', image: `${path}photo-060.jpg` },
	{ alt: 'Adria in the woods', image: `${path}photo-061.jpg` },
	{ alt: 'Adria in the woods', image: `${path}photo-062.jpg` },
	{ alt: 'Matt in the woods', image: `${path}photo-063.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-064.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-065.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-066.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-068.jpg` },
	{ alt: 'Booze', image: `${path}photo-145.jpg` },
	{ alt: 'Table setting', image: `${path}photo-148.jpg` },
	{ alt: 'Table setting', image: `${path}photo-149.jpg` },
	{ alt: 'Table setting', image: `${path}photo-150.jpg` },
	{ alt: 'Table setting', image: `${path}photo-151.jpg` },
	{ alt: 'Table setting', image: `${path}photo-152.jpg` },
	{ alt: 'Table setting', image: `${path}photo-153.jpg` },
	{ alt: 'Matt posing', image: `${path}photo-155.jpg` },
	{ alt: 'The Lodge at Elk Valley in Divide, CO', image: `${path}photo-156.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-202.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-203.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-204.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-205.jpg` },
	{ alt: 'Boquet', image: `${path}photo-206.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-207.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-208.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-209.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-210.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-211.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-212.jpg` },
	{ alt: 'Adria posing', image: `${path}photo-213.jpg` },
	{ alt: 'Matt posing', image: `${path}photo-214.jpg` },
	{ alt: 'Matt posing', image: `${path}photo-215.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-216.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-217.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-218.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-219.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-220.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-221.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-222.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-223.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-224.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-225.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-226.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-227.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-228.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-229.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-230.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-231.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-232.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-233.jpg` },
	{ alt: 'Matt and Adria in the woods', image: `${path}photo-234.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-235.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-236.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-237.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-238.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-239.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-240.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-241.jpg` },
	{ alt: 'Table setting', image: `${path}photo-242.jpg` },
	{ alt: 'Table setting', image: `${path}photo-243.jpg` },
	{ alt: 'Table setting', image: `${path}photo-244.jpg` },
	{ alt: 'Table setting', image: `${path}photo-245.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-249.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-250.jpg` },
	{ alt: 'Matt and Adria', image: `${path}photo-252.jpg` },
	{ alt: 'Matt opening champagne', image: `${path}photo-260.jpg` },
	{ alt: 'Cake', image: `${path}photo-273.jpg` },
	{ alt: 'Cake', image: `${path}photo-274.jpg` },
	{ alt: 'Cake', image: `${path}photo-275.jpg` },
	{ alt: 'Pillow with rings', image: `${path}photo-276.jpg` },
	{ alt: 'Pillow with rings', image: `${path}photo-277.jpg` },
	{ alt: 'Vows and rings', image: `${path}photo-278.jpg` },
	{ alt: 'Vows and rings', image: `${path}photo-279.jpg` },
	{ alt: 'Booze', image: `${path}photo-280.jpg` },
	{ alt: 'Booze', image: `${path}photo-281.jpg` },
	{ alt: 'Sunset in Divide, CO', image: `${path}photo-282.jpg` },
	{ alt: 'Cozy fire', image: `${path}photo-307.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-308.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-309.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-310.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-311.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-312.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-313.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-314.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-315.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-316.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-317.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-318.jpg` },
	{ alt: 'Matt and Adria commence cake cutting', image: `${path}photo-319.jpg` },
];
